### ISSUE TITLE
Wrong interceptor key in getRESTFilters

### ISSUE THREAD

**Issue by itsmefox** [Viascom/groundwork#18]
The method `getRESTFilters` in Request.java has a bug. 
The wrong key is use to load the interceptors.

See: https://sonarqube.com/issues#issues=AVkgmU0J5BQvDmAJKdDT
See: https://sonarqube.com/issues#issues=AVkglpIi5BQvDmAJKdBX

**Comment by nik-sta** [comment]
@patrickboesch should now be fixed. pls review
