### ISSUE TITLE
FoxHttpClient documentation missing

### ISSUE THREAD

**Issue by marshalluous** [Viascom/groundwork#27]
Hi
I was looking for the documentation of the FoxHttpClient? And is a default Client created in each request?
Best regards

**Comment by nik-sta** [comment]
Hi @marshalluous :-)

Thanks for your interest in FoxHttp :-) ... May you tell me what exactly you missed in our documentation connected to the FoxHttpClient?

If you don't specify a FoxHttpClient it will be used a new default client.

Cheers, Nikola

**Comment by marshalluous** [comment]
Hi Nikola
I was searching for the whole documentation. I want to create a Client myself and want to know what/how I can do that. =)

**Comment by nik-sta** [comment]
Ok ... you can always look into the javadoc for explanations of the methods. A documentation in our wiki will be added as soon as possible.  Thanks for your contribution.
