### ISSUE TITLE
ServiceResult documentation

### ISSUE THREAD

**Issue by marshalluous** [Viascom/groundwork#28]
Could you make an example with a specific Object and a ServiceResult and what does it do?

**Comment by marshalluous** [comment]
means: how can I parse my JSON Response into an Java-object I have created?

**Comment by nik-sta** [comment]
Hi @marshalluous :) 

The short answer is: with the method **getContent()**

But it's important that the backend server replies to your request with the service-result. So he've to implement the service-result. 

As an example code snippet it could look like this in your api java class:

``` java
public User login(User user) throws FoxHttpException {
        FoxHttpResponse<User> response = new LoginRequest().execute(getUrl(), user, client);
        return new FoxHttpServiceResultResponse<User>(response).getContent(User.class);
}
```
